# Generated by Django 4.2.3 on 2023-11-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='ndoctors',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
