# Generated by Django 4.2.3 on 2023-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0005_alter_departments_ndoctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='logintb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('utype', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
